### ISSUE TITLE
Sketchpacks app

### ISSUE THREAD

**Issue by mikeprecious** [fuggfuggfugg/sketch-dynamic-button-3.5#34]
Hi there, wondered if you pushed the symbol support version of Dynamic Button to where Sketchpacks app can access it.

**Comment by fuggfuggfugg** [comment]
@mikeprecious The basic symbol support has been merged in. Nested symbol is still incomplete.

**Comment by mikeprecious** [comment]
Thanks @fuggfuggfugg ! Used Sketchpacks the other to remove and update the Dynamic Button plugin and the state of the plugin that got installed on update removed the symbol functionality that existed from the prior, manual installation. I've actually had to manually download and install the plugin from the symbol branch state on Github to get the symbol support functionality. Seems like there's something going on with Sketchpacks.

**Comment by fuggfuggfugg** [comment]
Hmm, That's weird. I'll try this tonight and get back. The symbol branch I thought I had merged it in. I'll try re-installing from Sketchpacks. Thanks for notifying me about the issue.

**Comment by fuggfuggfugg** [comment]
@mikeprecious I just uninstalled and re-installed from sketchpacks and the basic symbol works. 

Can you confirm which branch are you talking about? I merged
 https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/tree/sketch-symbols-fuck-yeah

I haven't merged the nested-symbols branch yet.

**Comment by mikeprecious** [comment]
@fuggfuggfugg apologies for the radio silence. 

I cannot recall my steps at the moment. I just updated the plugin via SketchPacks. I still get the legacy behaviour: I try to dynamically resize the symbol Cmd+J and it produces a grey box behind the symbol. If I dive into the symbol contents, everything is set up properly. For example 8:16 defined in the text layer name and the shape layer behind it, "BG".

**Comment by fuggfuggfugg** [comment]
I'll take a look tonight. 

If it's not much trouble, can I request a gif just so I can replicate it exactly?

**Comment by mikeprecious** [comment]
Wanted to follow-up. Haven't had a chance to create a GIF. Behaviour is exactly as described above. Will try to get a GIF over to you this weekend.

**Comment by fuggfuggfugg** [comment]
@mikeprecious Sorry for the delay. 

The code currently was very messy and getting hard to debug. I had to refactor the code so I could debug it better. I have ported the changes from the other branch. 

Issues Fixed: 
* From Symbol Master if you select the text, change padding and cmj+j, it will add the new padding to the symbol master and update all the children. 
* If you simply do cmd+j on symbol master, it will update all the children. 

I haven't updated sketchpacks yet, still trying for nested symbols one more time. 

Can you uninstall the installed plugin and manually install this one?  
[DynamicButton3.5-rewrite.sketchplugin.zip](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/files/1255016/DynamicButton3.5-rewrite.sketchplugin.zip)

If something is not working (& was working in earlier version) do let me know. If all is well, I'll proceed to push the changes to sketchpacks by tomorrow.
